//! Deterministic generation of a source-able `cpd_vars.sh`.
//!
//! Responsibilities:
//! - Emit one `export KEY='value'` line per required variable, in the fixed
//!   [`crate::spec::SPEC`] order so output is byte-identical across runs (AC9).
//! - Safely single-quote every value so the file sources back the *exact*
//!   input, with no shell expansion or injection (AC7).
//! - Produce syntactically valid shell (AC2).
//!
//! The [`Config`] passed in is assumed already validated; generation does not
//! re-validate. Generation never contacts a cluster.

use crate::spec::SPEC;
use std::collections::BTreeMap;

/// A fully-collected, validated configuration: variable name -> value.
pub type Config = BTreeMap<String, String>;

/// Single-quote a value for POSIX shell so that sourcing the file reproduces
/// the exact original string.
///
/// Inside single quotes the shell treats every character literally, so the only
/// character needing care is the single quote itself. The classic, portable
/// escape for an embedded `'` is to close the quote, emit an escaped quote, and
/// reopen: `'\''`.
///
/// Examples:
/// - `abc`        -> `'abc'`
/// - `p@ss w$rd`  -> `'p@ss w$rd'`   (space and `$` are inert inside '...')
/// - `it's`       -> `'it'\''s'`
pub fn shell_quote(value: &str) -> String {
    let mut out = String::with_capacity(value.len() + 2);
    out.push('\'');
    for ch in value.chars() {
        if ch == '\'' {
            out.push_str("'\\''");
        } else {
            out.push(ch);
        }
    }
    out.push('\'');
    out
}

/// Render the full `cpd_vars.sh` contents from a validated [`Config`].
///
/// Output is deterministic: a fixed header (no timestamps, no random ordering)
/// followed by one `export` line per variable in [`SPEC`] order. The caller is
/// responsible for having validated `config`; any required variable missing
/// here is a programming error and panics, because generation must never silently
/// emit a partial file.
pub fn render(config: &Config) -> String {
    let mut out = String::new();
    out.push_str("#!/usr/bin/env bash\n");
    out.push_str("# cpd_vars.sh — watsonx.data install configuration\n");
    out.push_str("# Generated by wxd-config. Do NOT commit: this file carries credentials.\n");
    out.push_str("# Source it before running the install: `source ./cpd_vars.sh`\n");
    out.push('\n');

    for spec in SPEC {
        let value = config.get(spec.name).unwrap_or_else(|| {
            panic!(
                "generate::render called with missing required variable '{}' — \
                 config must be validated before generation",
                spec.name
            )
        });
        out.push_str("export ");
        out.push_str(spec.name);
        out.push('=');
        out.push_str(&shell_quote(value));
        out.push('\n');
    }

    out
}

#[cfg(test)]
mod tests {
    use super::*;

    fn full_config() -> Config {
        let mut c = Config::new();
        for spec in SPEC {
            c.insert(spec.name.to_string(), format!("val-{}", spec.name));
        }
        c
    }

    // ---- shell_quote (AC7) ----

    #[test]
    fn quotes_plain_value() {
        assert_eq!(shell_quote("abc"), "'abc'");
    }

    #[test]
    fn quotes_value_with_spaces_and_dollar() {
        assert_eq!(shell_quote("p@ss w$rd"), "'p@ss w$rd'");
    }

    #[test]
    fn quotes_value_with_double_quote_and_backtick() {
        assert_eq!(shell_quote("a\"b`c"), "'a\"b`c'");
    }

    #[test]
    fn escapes_embedded_single_quote() {
        assert_eq!(shell_quote("it's"), "'it'\\''s'");
    }

    #[test]
    fn quotes_empty_string() {
        assert_eq!(shell_quote(""), "''");
    }

    // ---- render (AC2, AC9) ----

    #[test]
    fn render_contains_every_required_var() {
        let rendered = render(&full_config());
        for spec in SPEC {
            assert!(
                rendered.contains(&format!("export {}=", spec.name)),
                "missing export for {}",
                spec.name
            );
        }
    }

    #[test]
    fn render_is_deterministic() {
        let config = full_config();
        assert_eq!(render(&config), render(&config));
    }

    #[test]
    fn render_emits_in_spec_order() {
        let rendered = render(&full_config());
        let mut last = 0usize;
        for spec in SPEC {
            let needle = format!("export {}=", spec.name);
            let pos = rendered.find(&needle).expect("var present");
            assert!(pos >= last, "{} out of order", spec.name);
            last = pos;
        }
    }

    #[test]
    fn render_starts_with_shebang() {
        assert!(render(&full_config()).starts_with("#!/usr/bin/env bash\n"));
    }

    #[test]
    #[should_panic(expected = "missing required variable")]
    fn render_panics_on_incomplete_config() {
        let mut c = full_config();
        c.remove("VERSION");
        let _ = render(&c);
    }
}
